#!/bin/bash
source ./gpu-simulator/setup_environment.sh
time=$(date +%Y%m%d-%H%M)
./util/job_launching/run_simulations.py -B vulkan:pbrtexture_2k -C ORIN-SASS,ORIN-SASS-concurrent-7GR-finegrain,ORIN-SASS-concurrent-8GR-finegrain,ORIN-SASS-concurrent-9GR-finegrain,ORIN-SASS-concurrent-10GR-finegrain,ORIN-SASS-concurrent-11GR-finegrain,ORIN-SASS-concurrent-12GR-finegrain,ORIN-SASS-concurrent-13GR-finegrain -T ./hw_run/traces/vulkan/ -N run-$time-pbrtexture_2k
./util/job_launching/run_simulations.py -B vulkan:pbrtexture_4k -C ORIN-SASS,ORIN-SASS-concurrent-7GR-finegrain,ORIN-SASS-concurrent-8GR-finegrain,ORIN-SASS-concurrent-9GR-finegrain,ORIN-SASS-concurrent-10GR-finegrain,ORIN-SASS-concurrent-11GR-finegrain,ORIN-SASS-concurrent-12GR-finegrain,ORIN-SASS-concurrent-13GR-finegrain -T ./hw_run/traces/vulkan/ -N run-$time-pbrtexture_4k
./util/job_launching/run_simulations.py -B vulkan:instancing_2k -C ORIN-SASS,ORIN-SASS-concurrent-7GR-finegrain,ORIN-SASS-concurrent-8GR-finegrain,ORIN-SASS-concurrent-9GR-finegrain,ORIN-SASS-concurrent-10GR-finegrain,ORIN-SASS-concurrent-11GR-finegrain,ORIN-SASS-concurrent-12GR-finegrain,ORIN-SASS-concurrent-13GR-finegrain -T ./hw_run/traces/vulkan/ -N run-$time-instancing_2k
./util/job_launching/run_simulations.py -B vulkan:instancing_4k -C ORIN-SASS,ORIN-SASS-concurrent-7GR-finegrain,ORIN-SASS-concurrent-8GR-finegrain,ORIN-SASS-concurrent-9GR-finegrain,ORIN-SASS-concurrent-10GR-finegrain,ORIN-SASS-concurrent-11GR-finegrain,ORIN-SASS-concurrent-12GR-finegrain,ORIN-SASS-concurrent-13GR-finegrain -T ./hw_run/traces/vulkan/ -N run-$time-instancing_4k
./util/job_launching/run_simulations.py -B vulkan:render_passes_2k -C ORIN-SASS,ORIN-SASS-concurrent-7GR-finegrain,ORIN-SASS-concurrent-8GR-finegrain,ORIN-SASS-concurrent-9GR-finegrain,ORIN-SASS-concurrent-10GR-finegrain,ORIN-SASS-concurrent-11GR-finegrain,ORIN-SASS-concurrent-12GR-finegrain,ORIN-SASS-concurrent-13GR-finegrain -T ./hw_run/traces/vulkan/ -N run-$time-render_passes_2k
./util/job_launching/run_simulations.py -B vulkan:render_passes_4k -C ORIN-SASS,ORIN-SASS-concurrent-7GR-finegrain,ORIN-SASS-concurrent-8GR-finegrain,ORIN-SASS-concurrent-9GR-finegrain,ORIN-SASS-concurrent-10GR-finegrain,ORIN-SASS-concurrent-11GR-finegrain,ORIN-SASS-concurrent-12GR-finegrain,ORIN-SASS-concurrent-13GR-finegrain -T ./hw_run/traces/vulkan/ -N run-$time-render_passes_4k
echo run-$time
