export DATA_ROOT="$( cd "$( dirname "$BASH_SOURCE" )" && pwd )"
TITANX_PASCAL_DATA=$DATA_ROOT/TITAN-X-PASCAL
P100_PASCAL_DATA=$DATA_ROOT/TESLA-P100
FERMI_GTX480_DATA=$DATA_ROOT/GTX480
1080Ti_DATA=$DATA_ROOT/1080Ti

rm -rf $TITANX_PASCAL_DATA
rm -rf $P100_PASCAL_DATA
rm -rf $FERMI_GTX480_DATA
rm -rf $1080Ti_DATA
