
all:
	$(MAKE) -C tracer_tool
	$(MAKE) -C tracer_tool/traces-processing
	$(MAKE) -C others/spinlock_tool
#$(MAKE) -C silicon_checkpoint_tool

clean:
	$(MAKE) clean -C tracer_tool
	$(MAKE) clean -C tracer_tool/traces-processing
