name: Weekly Tests

on:
  workflow_dispatch:  # manually dispatch
  # push:
  schedule:
    - cron: '0 20 * * FRI'  # 8:00 PM every Friday

jobs:
  Tracer-Weekly:
    if: ${{ github.repository == 'accel-sim/accel-sim-framework' || github.event_name == 'workflow_dispatch' }}
    runs-on: tgrogers-gpu01
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - name: Setup Environment
        run: |
          rm -rf env-setup
          git clone --quiet git@github.com:purdue-aalp/env-setup.git 
          cd env-setup 
          git checkout cluster-ubuntu
      - name: Build Tracer
        run: |
          source ./env-setup/12.8_env_setup.sh
          ./util/tracer_nvbit/install_nvbit.sh
          make clean -C ./util/tracer_nvbit/
          make -C ./util/tracer_nvbit/
      - name: build applications
        run: |
          source ./env-setup/12.8_env_setup.sh
          export PATH=/home/tgrogers-raid/a/common/python2:$PATH
          rm -rf ./gpu-app-collection/
          git clone --quiet git@github.com:accel-sim/gpu-app-collection.git
          git -C ./gpu-app-collection/ submodule update --init -- ./src/cuda/cuda-samples
          source ./gpu-app-collection/src/setup_environment
          ln -s /home/tgrogers-raid/a/common/data_dirs ./gpu-app-collection/
          make -j8 -C ./gpu-app-collection/src rodinia-3.1
          make -j8 -C ./gpu-app-collection/src GPU_Microbenchmark
          # make -j8 -C ./gpu-app-collection/src Deepbench_nvidia
          # make -j8 -C ./gpu-app-collection/src parboil
          # make -j8 -C ./gpu-app-collection/src polybench
          # make -j8 -C ./gpu-app-collection/src cutlass
      - name: generate traces
        run: |
          source ./env-setup/12.8_env_setup.sh
          source ./gpu-app-collection/src/setup_environment
          rm -rf ./hw_run/
          rm -rf /scratch/tgrogers-disk01/a/common/for-sharing/$USER/nightly-traces
          mkdir -p /scratch/tgrogers-disk01/a/common/for-sharing/$USER/nightly-traces
          ln -s /scratch/tgrogers-disk01/a/common/for-sharing/$USER/nightly-traces ./hw_run
          ./util/tracer_nvbit/run_hw_trace.py -B rodinia-3.1,GPU_Microbenchmark -D 7
          # ./util/tracer_nvbit/run_hw_trace.py -B rodinia-3.1,GPU_Microbenchmark,parboil,polybench,cutlass_5_trace,Deepbench_nvidia_tencore,Deepbench_nvidia_normal -D 7
      - name: generate-spinlock-traces-spinlock_handling
        run: |
          source ./env-setup/12.8_env_setup.sh
          source ./gpu-app-collection/src/setup_environment
          rm -rf ./hw_run/
          ./util/tracer_nvbit/run_hw_trace.py -B Spinlock -D 7 --spinlock_handling fast_forward
          mv ./hw_run ./hw_run_fast_forward
          ./util/tracer_nvbit/run_hw_trace.py -B Spinlock -D 7 --spinlock_handling none
          mv ./hw_run ./hw_run_none
      - name: test-new-traces-spinlock_handling
        # Test only fast-forwarded traces as the none one takes too long to run (~2-3 hr)
        run: |
          source ./env-setup/12.8_env_setup.sh
          source ./gpu-simulator/setup_environment.sh
          ./util/job_launching/run_simulations.py -B Spinlock -C QV100-SASS -T ./hw_run_fast_forward/traces/device-7/ -N spinlock-microbenchmark-$$-fast_forward
          ./util/job_launching/monitor_func_test.py -I -v -s spinlock-stats-per-app.csv -N spinlock-microbenchmark-$$-fast_forward
          # ./util/job_launching/run_simulations.py -B Spinlock -C QV100-SASS -T ./hw_run_none/traces/device-7/ -N spinlock-microbenchmark-$$-none
          # ./util/job_launching/monitor_func_test.py -I -v -s spinlock-stats-per-app.csv -N spinlock-microbenchmark-$$-none
  SASS-Weekly:
    needs: [Tracer-Weekly]
    if: ${{ github.repository == 'accel-sim/accel-sim-framework' || github.event_name == 'workflow_dispatch' }}
    runs-on: tgrogers-raid 
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - name: Setup Environment
        run: |
          rm -rf env-setup
          git clone --quiet git@github.com:purdue-aalp/env-setup.git 
          cd env-setup 
          git checkout cluster-ubuntu
      - name: Build Accel-Sim
        run: |
          source ./env-setup/12.8_env_setup.sh
          rm -rf ./gpu-simulator/gpgpu-sim
          source ./gpu-simulator/setup_environment.sh
          make clean -C gpu-simulator
          make -j -C gpu-simulator
      - name: run SASS
        run: |
          source ./env-setup/12.8_env_setup.sh
          source ./gpu-simulator/setup_environment.sh
          ln -s /scratch/tgrogers-disk01/a/common/for-sharing/$USER/nightly-traces ./hw_run
          # ./util/job_launching/run_simulations.py -B rodinia-3.1,GPU_Microbenchmark,sdk-4.2-scaled,parboil,polybench,cutlass_5_trace,Deepbench_nvidia_tencore,Deepbench_nvidia_normal -C QV100-SASS-5B_INSN -T ./hw_run/traces/device-7/12.8 -N weekly-$$ -M 70G
          ./util/job_launching/run_simulations.py -B rodinia-3.1,GPU_Microbenchmark -C QV100-SASS-5B_INSN -T ./hw_run/traces/device-7/12.8 -N weekly-$$ -M 70G
          ./util/job_launching/monitor_func_test.py -T 12 -S 1800 -I -v -s weekly-stats-per-app.csv -N weekly-$$
